sonar.projectKey=Tight-Line_creel
sonar.organization=tight-line
sonar.projectName=creel
sonar.projectVersion=0.1.1
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,**/vendor/**,gen/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=cmd/**/*
sonar.sourceEncoding=UTF-8
