DROP TABLE IF EXISTS system_account_keys;
DROP TABLE IF EXISTS system_accounts;
DROP TABLE IF EXISTS links;
DROP TABLE IF EXISTS chunks;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS topic_grants;
DROP TABLE IF EXISTS topics;
