apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-creel
  labels:
    app.kubernetes.io/name: creel
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      name: grpc
    - port: {{ .Values.service.rest.port }}
      targetPort: rest
      name: rest
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      name: metrics
  selector:
    app.kubernetes.io/name: creel
    app.kubernetes.io/instance: {{ .Release.Name }}
