"""Creel Python SDK; a REST client for the Creel memory-as-a-service platform."""

from creel.client import CreelClient
from creel.exceptions import CreelError
from creel.models import (
    Chunk,
    ChunkingStrategy,
    CompactResponse,
    CompactionRecord,
    Document,
    DocumentCitation,
    GetCompactionHistoryResponse,
    GetContextResponse,
    HealthResponse,
    IngestChunksResponse,
    Link,
    ListDocumentsResponse,
    ListGrantsResponse,
    ListJobsResponse,
    ListLinksResponse,
    ListMemoriesResponse,
    ListScopesResponse,
    ListTopicsResponse,
    Memory,
    MemorySearchResult,
    ProcessingJob,
    RequestCompactionResponse,
    SearchMemoriesResponse,
    SearchResponse,
    SearchResult,
    Topic,
    TopicGrant,
    UncompactResponse,
    UploadDocumentResponse,
)

__all__ = [
    "CreelClient",
    "CreelError",
    "Chunk",
    "ChunkingStrategy",
    "CompactResponse",
    "CompactionRecord",
    "Document",
    "DocumentCitation",
    "GetCompactionHistoryResponse",
    "GetContextResponse",
    "HealthResponse",
    "IngestChunksResponse",
    "Link",
    "ListDocumentsResponse",
    "ListGrantsResponse",
    "ListJobsResponse",
    "ListLinksResponse",
    "ListMemoriesResponse",
    "ListScopesResponse",
    "ListTopicsResponse",
    "Memory",
    "MemorySearchResult",
    "ProcessingJob",
    "RequestCompactionResponse",
    "SearchMemoriesResponse",
    "SearchResponse",
    "SearchResult",
    "Topic",
    "TopicGrant",
    "UncompactResponse",
    "UploadDocumentResponse",
]
